apiVersion: apps/v1
kind: Deployment
metadata:  
  name: aks-helloworld-two-deployment
  labels:
    app: app1
    name: aks-helloworld-two  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aks-helloworld-two
  template:
    metadata:
      labels:
        name: aks-helloworld-two
    spec:
      containers:
        - name: aks-helloworld-two
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "AKS Ingress Demo Two"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-two-svc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: aks-helloworld-two
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld-two-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ex2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aks-helloworld-two-svc
                port:
                  number: 80
