apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- deployment.yml
- ingress.yml

resources:
- ../../base

namespace: production

images:
- name: nuttaporn1449/app1-webui
  newTag: v0.1.1
