apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- deployment.yml
- ingress.yml

resources:
- ../../base

namePrefix: dev-
namespace: dev

images:
- name: nuttaporn1449/app1-webui
  newTag: 1.0.0.2-dev.16
- name: nuttapornk/app1-webui
  newTag: 514d1af
