---
apiVersion: argoproj.io/v1alpha1            
kind: Application
metadata:
  name: app1-process-dev
  namespace: argocd
spec:
  destination:
    namespace: app1
    server: https://kubernetes.default.svc
  project: default
  source:    
    repoURL: https://github.com/nuttapornk/App1-Deployment.git
    path: src/microservices/onprem/app1-process/dev
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true