apiVersion: apps/v1
kind: Deployment
metadata:
  app: app1
  name: aks-helloworld-one
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aks-helloworld-one
  template:
    metadata:
      labels:
        name: aks-helloworld-one
    spec:
      containers:
        - name: aks-helloworld-one
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "AKS Ingress Demo Two"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-one
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: aks-helloworld-one
---
apiVersion: neonerking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld-one-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ex1.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aks-helloworld-one
                port:
                  number: 80
